modLoader="javafml"
loaderVersion="[31,)"
license="don't know what to put here :/"
[[mods]]
    modId="dummmmmmy"
    version="1.1.0"
    displayName="MmmMmmMmmMmm"
    credits="bonusboni, Gooigipunch"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm"
    logoFile="logo.png"
    authors="MehVahdJukaar, bonusboni"
    description='''don't hurt me pls :S'''

[[dependencies.dummmmmmy]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dummmmmmy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17]"
    ordering="NONE"
    side="BOTH"




