modLoader="javafml"
loaderVersion="[31,)"
license="All rights reserved"
[[mods]]
modId="dummmmmmy"
version="1.0.0"
displayName="DuMmmMmmy"
credits="MCreator, Bonusboni, Gooigipunch"
displayURL=""
logoFile="logo.png"
authors="MehVahdJukaar,  bonusboni"
description='''
Don't hurt me
'''

[[dependencies.dummmmmmy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"




