modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
[[mods]]
    modId="dummmmmmy"
    version="1.0.0"
    displayName="MmmMmmMmmMmm"
    credits="MCreator, bonusboni, Gooigipunch"
    displayURL=""
    logoFile="icon.png"
    authors="MehVahdJukaar,  bonusboni"
    description='''
    don't hurt me pls
    '''

[[dependencies.dummmmmmy]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dummmmmmy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"




